clear;
close all;

%Define the initial state variables

x0=[0;0;0;0];

m=0.15;J=750;Ca=1.5;h=0.1;k=5;g=9.81;

parameters=[m,J,Ca,h,k];

%% Search for a specified operating point for the model - platform_trim.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.12 and Simulink Control Design (TM) 6.1.
%
% Generated on: 21-May-2022 08:57:53

%% Specify the model name
model = 'platform_trim';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - platform_trim/S-Function Builder
opspec.States(1).x = [0;0;0.369;0.258];
opspec.States(1).Known = [true;true;false;false];

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - platform_trim/In1
opspec.Inputs(1).u = [0.256;0];
opspec.Inputs(1).Known = [false;true];

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - platform_trim/Out1
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
%%Exctract the equilibrium
xeq=op.States.x;
ueq=op.Inputs.u;

%Compute the linearized plant using linmod
[Ac,Bc0,Cc,Dc0]=linmod('platform_trim',xeq,ueq);

Bc=Bc0(:,1);  % Actuator column

Dc=Dc0(:,1);

%sampling time
Ts=0.5;

%Plant dimensions instrumental to LQ regulation

[nx,nu]=size(Bc);

%Let us compute discretized plant

platform_tc=ss(Ac,Bc,Cc,Dc);

platform_td=c2d(platform_tc,Ts);

%Extract the matrices

[A,B,C,D]=ssdata(platform_td);

%% Defining the matrices of the exosystem

Arc=0;

Cr=1;

% Discretize Arc  Ar=expm(Arc*Ts);

Ar=expm(Arc*Ts);

[nr,nr]=size(Ar);  % number of "references" generated by the exosystem

Cy=[1 0 0 0];    % Position track

%% Let us build the A, B matrices of the augmented system
Aaug=blkdiag(A,Ar);
Baug=[B;zeros(nr,nu)];

%% LQ performance matrices Q, R, M, S

Qy=1;

Sy=Qy;

Q=[Cy';-Cr']*Qy*[Cy -Cr];

S=[Cy';-Cr']*Sy*[Cy -Cr];

rho=0.01;

R=rho*eye(nu);

M=zeros(nu,nx+nr);


% Final time

tfin=70;

% Number of steps

N=ceil(tfin/Ts);

[Ft,Pt]=offline_lq_ric(Aaug,Baug,Q,R,S,M,N);

% ON-LINE PART

% Vectors collecting the state, input and time trend taken from Simulink

xseq=[];

useq=[];

tseq=[];

timesamp=[];

ref_seq=[];

% Initial perturbation w.r.t. the equilibrium

dx0=[0;0;0;0];

% Initial state of the reference generator (in this case, the step
% amplitude);

xrk=0.1;

xInitial=xeq+dx0; %the initial state is the equilibrium+deviation
                  %xInitial is an absolut state then we always must to
                  %the equilibrium state

 F=Ft(1,1:nx);      %  Feedback component

 Fv=Ft(1,nx+1:end); % Feedforward component

for i=1:N;

    t=(i-1)*Ts;

  
    u=[(-F*(xInitial-xeq)-Fv*xrk+ueq(1));ueq(2)]';  % control law as sum of feedback 
                                         % and feeforward components

    result=sim("platform_sim");
    % Let us collect the states from the simulink model


    % Merge this temporary variable inside the whole state variable

    xseq=[xseq result.xout'];

    % Inputs sequence mergin

    useq=[useq u(1).*ones(1,length(result.tout))];

    % Reference to be tracked stored for graphical purposes

    ref_seq=[ref_seq Cr*xrk];

    % Discrete time collected for graphical purposes

    timesamp=[timesamp (i-1)*Ts];

    % Analog time

    tseq=[tseq result.tout'];

    % xInitial update

    xInitial=result.xFinal';

    % Current state instrumental for feedback

    dx0=[result.xFinal'];

    % Tracking signal update

    xrk=Ar*xrk;

end;

% states

subplot(3,1,1);
plot(tseq,xseq(1,:), timesamp,ref_seq,'LineWidth',2);
grid;
title('Position');

subplot(3,1,2);
plot(tseq,xseq(3,:),'LineWidth',2);
grid;
title('Velocity');

subplot(3,1,3);
plot(tseq,useq, 'LineWidth',2);
grid;
title('Torque');




